export const MOCK_ROOMS = [
  {
    id: 1,
    name: 'Grand Deluxe Ocean View',
    roomType: 'DELUXE',
    pricePerNight: 2500000,
    capacity: 2,
    area: 45,
    image: '/room-deluxe.png',
    amenities: ['WiFi', 'Minibar', 'Bồn tắm', 'Ban công'],
    available: true,
    description:
      'Phòng Grand Deluxe Ocean View mang đến không gian sang trọng, cửa kính lớn hướng biển và tiện nghi hiện đại. Phù hợp cho 2 người, với ban công riêng và trải nghiệm nghỉ dưỡng cao cấp.',
  },
  {
    id: 2,
    name: 'Presidential Suite',
    roomType: 'SUITE',
    pricePerNight: 8500000,
    capacity: 4,
    area: 120,
    image: '/room-suite.png',
    amenities: ['WiFi', 'Bể bơi riêng', 'Butler', 'Phòng khách', 'Bếp'],
    available: true,
    description:
      'Presidential Suite sở hữu phòng khách rộng, bể bơi riêng và dịch vụ Butler cá nhân. Đây là lựa chọn hoàn hảo cho khách VIP và gia đình muốn trải nghiệm đẳng cấp.',
  },
  {
    id: 3,
    name: 'Superior Comfort Room',
    roomType: 'STANDARD',
    pricePerNight: 1200000,
    capacity: 2,
    area: 30,
    image: '/room-standard.png',
    amenities: ['WiFi', 'TV 55"', 'Điều hòa'],
    available: true,
    description:
      'Superior Comfort Room là lựa chọn tiết kiệm nhưng vẫn đầy đủ tiện nghi hiện đại cho chuyến đi công tác hoặc nghỉ dưỡng ngắn ngày.',
  },
  {
    id: 4,
    name: 'Family Deluxe Suite',
    roomType: 'DELUXE',
    pricePerNight: 3800000,
    capacity: 5,
    area: 75,
    image: '/room-deluxe.png',
    amenities: ['WiFi', '2 Phòng ngủ', 'Bếp nhỏ', 'Giường phụ'],
    available: true,
    description:
      'Family Deluxe Suite được thiết kế cho gia đình đông người với hai phòng ngủ riêng biệt và tiện ích bếp nhỏ thuận tiện.',
  },
  {
    id: 5,
    name: 'Classic Standard Room',
    roomType: 'STANDARD',
    pricePerNight: 950000,
    capacity: 1,
    area: 25,
    image: '/room-standard.png',
    amenities: ['WiFi', 'Điều hòa', 'Tủ lạnh nhỏ'],
    available: false,
    description:
      'Classic Standard Room phù hợp cho khách đi một mình hoặc khách doanh nhân cần nơi dừng chân gọn nhẹ, tiện nghi cơ bản.',
  },
  {
    id: 6,
    name: 'Honeymoon Ocean Suite',
    roomType: 'SUITE',
    pricePerNight: 6200000,
    capacity: 2,
    area: 90,
    image: '/room-suite.png',
    amenities: ['WiFi', 'Bồn tắm ngoài trời', 'Rượu vang', 'Hoa tươi'],
    available: true,
    description:
      'Honeymoon Ocean Suite thiết kế lãng mạn, từ phòng tắm ngoài trời đến dịch vụ hoa tươi và rượu vang chào đón.',
  },
  {
    id: 7,
    name: 'Executive Business Room',
    roomType: 'DELUXE',
    pricePerNight: 2200000,
    capacity: 2,
    area: 40,
    image: '/room-deluxe.png',
    amenities: ['WiFi tốc độ cao', 'Bàn làm việc', 'In ấn', 'Minibar'],
    available: true,
    description:
      'Executive Business Room được tối ưu cho khách công tác với bàn làm việc rộng rãi và kết nối internet tốc độ cao.',
  },
  {
    id: 8,
    name: 'Presidential Grand Suite',
    roomType: 'PRESIDENTIAL',
    pricePerNight: 15000000,
    capacity: 6,
    area: 250,
    image: '/room-suite.png',
    amenities: ['Butler riêng', 'Bể bơi', 'Phòng tập gym', 'Bếp trưởng'],
    available: true,
    description:
      'Presidential Grand Suite là đỉnh cao của trải nghiệm nghỉ dưỡng với các dịch vụ cá nhân hóa và không gian riêng tư toàn diện.',
  },
];
